---
- name: Determine Kafka's Broker ID
  ansible.builtin.set_fact:
    kafka_broker_id: "{{ groups['kafka_cluster'].index(inventory_hostname) + 1 }}"

- name: Creating the log directory for Kafka
  ansible.builtin.file:
    path: "{{ kafka_logs_dir }}"
    state: directory
    owner: "{{ kafka_service_user_name }}"
    group: "{{ kafka_service_group_name }}"
    mode: "0755"

- name: Configuring Kafka service
  ansible.builtin.template:
    src: "kafka-server.service.j2"
    dest: "/etc/systemd/system/kafka-server.service"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Reload systemd daemon

- name: Updating Kafka's configuration
  ansible.builtin.template:
    src: "server.properties.j2"
    dest: "{{ installation_dir }}/kafka/config/server.properties"
    owner: "{{ kafka_service_user_name }}"
    group: "{{ kafka_service_group_name }}"
    mode: "0644"
  notify:
    - Start kafka service
