---
- name: Checking pre-requisities on target Machine
  include_tasks: check-pre-requisities.yml

- name: Including playbook to install kafka and zookeeper
  include_tasks: install-kafka-zookeeper.yml

- name: Including playbook to configure zookeeper
  include_tasks: configure-zookeeper.yml
  when: "inventory_hostname in groups['zookeeper']"

- name: Including playbook to configure kafka
  include_tasks: configure-kafka.yml
  when: "inventory_hostname in groups['kafka']"
