---
# handlers file for osm_kafka_cluster
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Start zookeeper service
  ansible.builtin.service:
    name: zookeeper
    state: restarted
    enabled: true

- name: Start kafka service
  ansible.builtin.service:
    name: kafka-server
    state: restarted
    enabled: true
